# Generated by Django 4.2.5 on 2023-09-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6)),
                ('marca', models.CharField(max_length=10)),
                ('color_vehiculo', models.CharField(choices=[('1', 'ROJO'), ('2', 'AZUL'), ('3', 'VERDE')], max_length=1, verbose_name='color')),
                ('modelo', models.IntegerField()),
            ],
        ),
    ]
